{
 "title": "Pipeline Duration Report",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Project ID",
    "query": "SELECT DISTINCT project_id\nFROM gitlab_ci.pipelines"
   },
   {
    "name": "ref_type",
    "label": "Ref Type",
    "query": "SELECT DISTINCT CASE\n    WHEN ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n    WHEN ref IN ('main', 'master') THEN 'main'\n    WHEN tag THEN 'tag'\n    ELSE 'branch'\n  END AS pipeline_type\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "SELECT DISTINCT status \nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\n\nUNION ALL\n\nSELECT DISTINCT status \nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)"
   },
   { "name": "job_filter", "label": "Job Filter", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Durations (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(finished_at, 3), INTERVAL 1 day) AS time,\n  quantileTiming(0.95)(duration) AS duration,\n  CASE\n    WHEN ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n    WHEN ref IN ('main', 'master') THEN 'main'\n    WHEN tag THEN 'tag'\n    ELSE 'branch'\n  END AS ref_type\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id}\n  AND $__timeFilter(finished_at)\n  AND ref_type IN splitByChar(',', '${ref_type:raw}')\n  AND status IN splitByChar(',', '${status:raw}')\nGROUP BY time, ref_type\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Job Durations (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(jobs.finished_at, 3), INTERVAL 1 day) AS time,\n  quantileTiming(0.95)(jobs.duration) AS duration,\n  regexpExtract(jobs.name, '([^\\[\\]]+)(?:\\s\\[(.+?)\\])?') AS name\nFROM gitlab_ci.jobs AS jobs\n  INNER JOIN (\n    SELECT\n      jobs.id AS job_id,\n      CASE\n        WHEN pipelines.ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n        WHEN pipelines.ref IN ('main', 'master') THEN 'main'\n        WHEN pipelines.tag THEN 'tag'\n        ELSE 'branch'\n      END AS ref_type\n    FROM gitlab_ci.jobs AS jobs\n      INNER JOIN gitlab_ci.pipelines AS pipelines ON pipelines.id = jobs.pipeline.id\n    WHERE\n      pipelines.project_id = ${project_id}\n      AND $__timeFilter(jobs.finished_at)\n  ) AS pipeline_refs ON pipeline_refs.job_id = jobs.id\nWHERE jobs.pipeline.project_id = ${project_id}\n  AND $__timeFilter(jobs.finished_at)\n  AND pipeline_refs.ref_type IN splitByChar(',', '${ref_type:raw}')\n  AND status IN splitByChar(',', '${status:raw}')\n  AND match(jobs.name, '${job_filter:raw}')\nGROUP BY time, name\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Average Section Durations",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(sections.finished_at, 3), INTERVAL 1 day) AS time,\n  name,\n  avg(sections.duration) AS duration\nFROM gitlab_ci.sections AS sections\n  INNER JOIN (\n    SELECT\n      sections.id AS section_id,\n      CASE\n        WHEN pipelines.ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n        WHEN pipelines.ref IN ('main', 'master') THEN 'main'\n        WHEN pipelines.tag THEN 'tag'\n        ELSE 'branch'\n      END AS ref_type\n    FROM gitlab_ci.sections AS sections\n      INNER JOIN gitlab_ci.pipelines AS pipelines ON pipelines.id = sections.pipeline.id\n    WHERE\n      pipelines.project_id = ${project_id}\n      AND $__timeFilter(sections.finished_at)\n  ) AS pipeline_refs ON pipeline_refs.section_id = sections.id\nWHERE sections.pipeline.project_id = ${project_id}\n  AND $__timeFilter(sections.finished_at)\n  AND pipeline_refs.ref_type IN splitByChar(',', '${ref_type:raw}')\n  AND sections.job.status IN splitByChar(',', '${status:raw}')\n  AND match(sections.job.name, '${job_filter:raw}')\nGROUP BY time, name\nHAVING duration > 1\nORDER BY time ASC"
    }
   ]
  }
 ]
}