{
 "title": "GitLab CI - Project Overview",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_CLICKHOUSE", "query": "grafana-clickhouse-datasource" },
   {
    "name": "project_id",
    "label": "Project",
    "query": "SELECT DISTINCT id, path_with_namespace FROM gitlab_ci.projects ORDER BY path_with_namespace"
   }
  ]
 },
 "panels": [
  {
   "title": "Pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Sections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.sections\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(count(testcases.id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.testcases AS testcases\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testcases.pipeline_id = pipelines.id\nWHERE (pipelines.project_id = ${project_id}) AND $__timeFilter(pipelines.finished_at)\nGROUP BY $__timeInterval(finished_at) AS interval\nORDER BY interval"
    }
   ]
  },
  {
   "title": "Pipeline Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(status) AS success_count,\n  ( SELECT count() FROM gitlab_ci.pipelines WHERE project_id = ${project_id} AND $__timeFilter(finished_at) ) AS total_count \n  FROM gitlab_ci.pipelines\n  WHERE project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Job Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(status) AS success_count,\n  ( SELECT count() FROM gitlab_ci.jobs WHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)) AS total_count \n  FROM gitlab_ci.jobs\n  WHERE pipeline.project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(testsuites.success_count) / sum(testsuites.total_count - testsuites.skipped_count) AS success_ratio\nFROM gitlab_ci.testsuites AS testsuites\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testsuites.pipeline_id = pipelines.id\nWHERE\n  pipelines.project_id = '${project_id}' AND $__timeFilter(pipelines.finished_at)\nGROUP BY toStartOfHour(toDateTime64(pipelines.finished_at, 3)) AS time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pipeline Runs per $__interval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(finished_at) as time, status, count()\n  FROM gitlab_ci.pipelines \n  WHERE (project_id = '${project_id}') AND $__timeFilter(time)\n  GROUP BY status, time\n  ORDER BY time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Job Runs per $__interval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(finished_at) as time, status, count()\n  FROM gitlab_ci.jobs \n  WHERE (pipeline.project_id = '${project_id}') AND $__timeFilter(time)\n  GROUP BY status, time\n  ORDER BY time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pipelines Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(status)\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY status",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "table",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT id, toDateTime64(finished_at, 3) AS finished_at, status, source, ref, queued_duration, duration\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\n",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Jobs Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(status)\nFROM gitlab_ci.jobs \nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY status",
     "selectedFormat": 1
    }
   ]
  }
 ]
}