{
 "title": "GitLab CI - Project Merge Requests",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_CLICKHOUSE", "query": "grafana-clickhouse-datasource" },
   {
    "name": "project_id",
    "label": "Project",
    "query": "SELECT DISTINCT id, path_with_namespace FROM gitlab_ci.projects ORDER BY path_with_namespace"
   }
  ]
 },
 "panels": [
  {
   "title": "Open",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count()\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND state = 'opened'"
    }
   ]
  },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(count()) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND $__timeFilter(created_at)\nGROUP BY $__timeInterval(updated_at) AS interval\nORDER BY interval"
    }
   ]
  },
  {
   "title": "Merged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(count()) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND state = 'merged'\n  AND $__timeFilter(merged_at)\nGROUP BY $__timeInterval(merged_at) AS interval\nORDER BY interval"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(count()) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND state = 'closed'\n  AND $__timeFilter(closed_at)\nGROUP BY $__timeInterval(closed_at) AS interval\nORDER BY interval"
    }
   ]
  },
  {
   "title": "Pipelines (95th percentile)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quantileExact(0.95)(count) FROM (\nSELECT\n  count(pipelines.id) count\nFROM gitlab_ci.mergerequests AS mergerequests\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON mergerequests.iid = (\n    CASE\n      WHEN pipelines.ref LIKE 'refs/merge-requests/%' THEN toInt64(extract(pipelines.ref, 'merge-requests/(\\d+)/'))\n      ELSE 0\n    END\n  )\nWHERE mergerequests.project_id = ${project_id}\n  AND pipelines.source = 'merge_request_event'\n  AND pipelines.ref NOT LIKE 'refs/merge-requests/%/head'\n  AND $__timeFilter(pipelines.created_at)\nGROUP BY mergerequests.iid\n)"
    }
   ]
  },
  {
   "title": "Age (95th percentile)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  quantileExact(0.95)(\n    CASE\n      WHEN merged_at > 0 THEN merged_at - created_at\n      WHEN closed_at > 0 THEN closed_at - created_at\n      WHEN state = 'opened' THEN toFloat64(toUnixTimestamp(now('UTC'))) - created_at\n    END\n  ) AS age\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Events per Day",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(created_at, 3), INTERVAL 1 day) AS time,\n  state,\n  count()\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND $__timeFilter(time)\nGROUP BY state, time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top 10 Open Merge Requests by Age",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  concat('!', toString(iid), ' - ', title),\n  age('hour', toDateTime64(created_at, 3), now64(3, 'UTC'), 'UTC') AS age\nFROM gitlab_ci.mergerequests\nWHERE project_id = ${project_id}\n  AND state = 'opened'\nORDER BY age DESC\nLIMIT 10"
    }
   ]
  }
 ]
}