{
 "title": "GitLab CI - Duration Reports",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_CLICKHOUSE", "query": "grafana-clickhouse-datasource" },
   {
    "name": "project_id",
    "label": "Project",
    "query": "SELECT DISTINCT id, path_with_namespace FROM gitlab_ci.projects ORDER BY path_with_namespace"
   },
   {
    "name": "ref_type",
    "label": "Ref Type",
    "query": "SELECT DISTINCT CASE\n    WHEN ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n    WHEN ref IN ('main', 'master') THEN 'main'\n    WHEN tag THEN 'tag'\n    ELSE 'branch'\n  END AS pipeline_type\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "SELECT DISTINCT status \nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\n\nUNION ALL\n\nSELECT DISTINCT status \nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)"
   },
   { "name": "job_filter", "label": "Job Filter", "query": ".*" },
   { "name": "percentile", "query": "0.5, 0.75, 0.9, 0.95" },
   { "name": "interval_days", "query": "7" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Durations (${percentile} percentile) over ${interval_days} days",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(finished_at, 3), INTERVAL ${interval_days} day) AS time,\n  quantileTiming(${percentile})(duration) AS duration,\n  count(),\n  CASE\n    WHEN ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n    WHEN ref IN ('main', 'master') THEN 'main'\n    WHEN tag THEN 'tag'\n    ELSE 'branch'\n  END AS ref_type\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id}\n  AND $__timeFilter(finished_at)\n  AND ref_type IN splitByChar(',', '${ref_type:raw}')\n  AND status IN splitByChar(',', '${status:raw}')\nGROUP BY time, ref_type\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Job Durations (${percentile} percentile) over ${interval_days} days",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(jobs.finished_at, 3), INTERVAL ${interval_days} day) AS time,\n  quantileTiming(${percentile})(jobs.duration) AS duration,\n  regexpExtract(jobs.name, '([^\\[\\]]+)(?:\\s\\[(.+?)\\])?') AS name\nFROM gitlab_ci.jobs AS jobs\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON pipelines.id = jobs.pipeline.id\nWHERE pipelines.project_id = ${project_id}\n  AND $__timeFilter(pipelines.finished_at)\n  AND CASE\n      WHEN pipelines.ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n      WHEN pipelines.ref IN ('main', 'master') THEN 'main'\n      WHEN pipelines.tag THEN 'tag'\n      ELSE 'branch'\n    END IN splitByChar(',', '${ref_type:raw}')\n  AND pipelines.status IN splitByChar(',', '${status:raw}')\n  AND match(jobs.name, '${job_filter:raw}')\nGROUP BY time, name\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Section Durations (${percentile} percentile) over ${interval_days} days",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime64(sections.finished_at, 3), INTERVAL ${interval_days} day) AS time,\n  name,\n  quantileTiming(${percentile})(sections.duration) AS duration\nFROM gitlab_ci.sections AS sections\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON pipelines.id = sections.pipeline.id\nWHERE pipelines.project_id = ${project_id}\n  AND $__timeFilter(pipelines.finished_at)\n  AND CASE\n      WHEN pipelines.ref LIKE 'refs/merge-requests/%' THEN 'merge-request'\n      WHEN pipelines.ref IN ('main', 'master') THEN 'main'\n      WHEN pipelines.tag THEN 'tag'\n      ELSE 'branch'\n    END IN splitByChar(',', '${ref_type:raw}')\n  AND pipelines.status IN splitByChar(',', '${status:raw}')\n  AND match(sections.job.name, '${job_filter:raw}')\nGROUP BY time, name\nORDER BY time ASC"
    }
   ]
  }
 ]
}