---
apiVersion: v2
name: gitlab-exporter-clickhouse-recorder
description: A gRPC endpoint for gitlab-exporter that records data in ClickHouse.
type: application

version: 1.9.1
appVersion: "v0.10.1"

